services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receitas-challenge-app
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=teste_receitas_rg_sistemas
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: receitas-challenge-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_receitas_rg_sistemas
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
